services:
  - type: web
    name: hydra-scanner-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements_render.txt
    startCommand: python bot_render.py
    envVars:
      - key: BOT_TOKEN
        value: 8307126286:AAHIZJg7Zr47bCoFAXNHJydTA-r1vpWcj5k
      - key: ADMIN_USER_ID
        value: 7012262263